import { DevtoolsProvider } from "@providers/devtools";
import { GitHubBanner, Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import React, { Suspense } from "react";
import { ThemeProvider } from "../providers/ThemeProvider";
import { SidebarProvider } from "../providers/sidebar-provider/sidebar-provider";

import { adminAuthProviderClient } from "@providers/auth-provider/auth-provider.client";
import { dataProvider } from "@providers/data-provider";
import "@styles/global.css";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense>

          <RefineKbarProvider>

              <ThemeProvider>
                     <SidebarProvider>
              <Refine
                routerProvider={routerProvider}
                authProvider={adminAuthProviderClient}
                dataProvider={dataProvider}
                resources={[
                  {
                    name: "admin",
                    list: "/admin",
                    create: "/admin/create",
                    edit: "/admin/edit/:id",
                    show: "/admin/show/:id",
                    meta: {
                      canDelete: true,
                    },
                  },
                  {
                    name: "categories",
                    list: "/categories",
                    create: "/categories/create",
                    edit: "/categories/edit/:id",
                    show: "/categories/show/:id",
                    meta: {
                      canDelete: true,
                    },
                  },
                ]}
                options={{
                  syncWithLocation: true,
                  warnWhenUnsavedChanges: true,
              projectId: "tendpwtatawlyxhmmdae",
                }}
              >
                {children}
                
                <RefineKbar />
                
              </Refine>
              </SidebarProvider>
              </ThemeProvider>

          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>
  );
}
